"""create chunk embeddings table

Revision ID: 299a2b9078d2
Revises: e1c929919150
Create Date: 2026-09-11

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "299a2b9078d2"
down_revision: str | Sequence[str] | None = "e1c929919150"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunk_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_chunk_id", sa.UUID(), nullable=False),
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "embedding",
            Vector(1536),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_chunk_id"],
            ["document_chunks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_chunk_id",
            "embedding_model",
            name="uq_chunk_embeddings_chunk_model",
        ),
    )

    op.create_index(
        op.f("ix_chunk_embeddings_document_chunk_id"),
        "chunk_embeddings",
        ["document_chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chunk_embeddings_organization_id"),
        "chunk_embeddings",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chunk_embeddings_organization_id"),
        table_name="chunk_embeddings",
    )
    op.drop_index(
        op.f("ix_chunk_embeddings_document_chunk_id"),
        table_name="chunk_embeddings",
    )
    op.drop_table("chunk_embeddings")
    # ### end Alembic commands ###