"""add approval proposals

Revision ID: 9bb5d137f10b
Revises: 75de4042f72e
Create Date: 2026-09-18 14:01:07.270763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bb5d137f10b'
down_revision: Union[str, Sequence[str], None] = '75de4042f72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_proposals_created_by_user_id'), 'approval_proposals', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_proposals_decided_by_user_id'), 'approval_proposals', ['decided_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_proposals_organization_id'), 'approval_proposals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_approval_proposals_status'), 'approval_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_proposals_status'), table_name='approval_proposals')
    op.drop_index(op.f('ix_approval_proposals_organization_id'), table_name='approval_proposals')
    op.drop_index(op.f('ix_approval_proposals_decided_by_user_id'), table_name='approval_proposals')
    op.drop_index(op.f('ix_approval_proposals_created_by_user_id'), table_name='approval_proposals')
    op.drop_table('approval_proposals')
    # ### end Alembic commands ###
